# Generated by Django 5.2.4 on 2025-08-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rename_completed_task_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='is_created',
        ),
    ]
